//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Football_Club.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Notification
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter Title :")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Enter Description :")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Enter Username :")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Enter Date :")]
        [Display(Name = " Date  ")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual SignUp SignUp { get; set; }
    }
}
