//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Football_Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamForMatch
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Note { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> MatchID { get; set; }
        public string Team { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
